version: 0.1.0

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore
  
build:
  project: LinqToSqlRetry.sln
  publish_nuget: true
  
artifacts:
  - path: LinqToSqlRetry\bin\Release\LinqToSqlRetry.dll
    name: LinqToSqlRetry.dll
  - path: '**\LinqToSqlRetry.*.nupkg'
 
deploy:
  provider: NuGet
  api_key:
    secure: amWULnZVsv5qbKalO9tM+5OvexyHcd36bp/t9D79yjaA/A5LVx+Uho7MG90d3/Bf
  artifact: /.*\.nupkg/
  
